#!/bin/bash

while getopts ":p:" opt; do
  case $opt in
    p) password="$OPTARG";;
  esac
done

if [ -z "$password" ]; then
  echo -n "Password: "
  read -s password
  echo
fi

swa=$(echo -n "$password" | sha512sum | awk '{print $1}' | base64)
swb=$(echo -n "$password" | sha256sum | awk '{print $1}' | base32)
swc=$(echo -n "$swb" | argon2 "$swa" -l 1024 -p 4 -t 4 -m 15 -r)
pwd=$(echo -n "$password" | argon2 "$swc" -l 1024 -p 4 -t 4 -m 15 -r)

skip=0

for var in "$@"
do
  skip="$(($skip-1))"
  if [ "$var" = '-p' ]; then
    skip=2
  fi
  if [ $skip -le 0 ]; then
    if [ "${var: -4}" == ".enc" ]; then
      outname="${var%.*}"
      else
      outname="${var}.dec"
    fi

    if [ ! -f "$outname" ]; then
      openssl aes-256-cbc -iter 100000 -d -in "${var}" -out "$outname" -pass pass:$pwd
    fi
  fi
done
