#!/bin/bash

if [ $# -eq 0 ]
then
	echo "ERROR: No arguments supplied"
	exit 1
fi

SOFTPATH=$HOME/soft/$1

if [ -d "${SOFTPATH}" ]
then
	i=0

	for entry in "${SOFTPATH}"/*
	do
		if [ -d "${entry}" ]
		then
			((i=i+1))
			echo "${i})" $(basename "$entry")
		fi
	done

	if [[ $i -eq 0 ]]
	then
		echo "WARNING: ${SOFTPATH} is empty"
		exit 0
	fi

	i=0
	n=1

	if [[ $i -gt 1 ]]
	then
		printf "	Select N dir: "
		read n
	fi

	for entry in "${SOFTPATH}"/*
	do
		if [ -d "${entry}" ]
		then
			((i=i+1))
			if [[ $i -eq $n ]]
			then
				if [ -f "${entry}/getenv.sh" ]
				then
					echo "	Selected " $(basename "$entry")
					source "${entry}/getenv.sh"
				else
					echo "ERROR: File not found ${entry}/getenv.sh"
					exit 1
				fi
			fi
		fi
	done
fi

$SHELL