#!/bin/bash

if [ $# -eq 0 ]
then
	echo "ERROR: No arguments supplied"
	exit 1
fi

SOFTPATH=$HOME/soft/$1

if [ -d "${SOFTPATH}" ]
then
	i=0

	for entry in "${SOFTPATH}"/*
	do
		if [ -d "${entry}" ]
		then
			((i=i+1))
			echo "${i})" $(basename "$entry")
		fi
	done

	if [[ $i -eq 0 ]]
	then
		echo "WARNING: ${SOFTPATH} is empty"
		exit 0
	fi

	n=1

	if [[ $i -gt 1 ]]
	then
		printf "Select ${1} dir: "
		read n
	fi

	i=0

	for entry in "${SOFTPATH}"/*
	do
		if [ -d "${entry}" ]
		then
			((i=i+1))
			if [[ $i -eq $n ]]
			then
				echo "Selected ${1}/"$(basename "$entry")
				if [ -f "${entry}/getenv.sh" ]
				then
					source "${entry}/getenv.sh"
				else
					export PATH=$PATH:${entry}
				fi
				$SHELL
			fi
		fi
	done
else
	echo "Error: ${SOFTPATH} not found"
fi
